### ISSUE TITLE
GET v1/videos/videoreference/:uuid returns a list

### ISSUE THREAD

**Issue by kevinsbarnard** [mbari-media-management/vampire-squid#10]
Hey @hohonuuli,

One of the endpoints that VARS Localize uses (`GET v1/videos/videoreference/:uuid`) had a minor schema change in the recent rewrite. For some reason, even though the video to video reference relation is 1-many, finding a video by its video reference now returns a list.

Example: http://m3.shore.mbari.org/vam/v1/videos/videoreference/d3a914e8-1a1b-4272-b9e7-421e4167c4da

The implementation seems to map the single returned video into a list: 

https://github.com/mbari-org/vampire-squid/blob/6c644ef4979883643d90accf9a8fb7a6065467c5/vampire-squid/src/main/scala/org/mbari/vampiresquid/repository/VideoDAO.scala#L36

https://github.com/mbari-org/vampire-squid/blob/6c644ef4979883643d90accf9a8fb7a6065467c5/vampire-squid/src/main/scala/org/mbari/vampiresquid/endpoints/VideoEndpoints.scala#L93-L105

This is a minor nit and I'm happy to work around it, though I reckon it should be a single returned object.

**Comment by hohonuuli** [comment]
@kevinsbarnard I'll take a look to see why that is. I'll get back to you shortly ...

**Comment by hohonuuli** [comment]
@kevinsbarnard Good catch. I've changed this in v1.0.6  to return a single item now. I've deployed this internally. (Would you pull the latest version and update rocinante?)

**Comment by kevinsbarnard** [comment]
Thanks for the quick fix @hohonuuli! I've redeployed on rocinante 👍🏻

**Comment by hohonuuli** [comment]
Just a note (for myself) it was returning a list to match the API from the older scalatra based vampire-squid. I reviewed vars-annotation to make sure that the change doesn't break anything in it.
